---
title: "From Untitled2"
author: "Praveen Kumar Neelappa"
date: "7 November 2017"
output:
  word_document: default
  html_document: default
---

```{r}
require(caret) #select tuning parameters
require(e1071) #SVM
```

```{r}

eddat <- read.csv('EdgarMDPraveen1.csv', as.is = T);
attach(eddat)

```


```{r}
dm6 <- eddat[which(group == 'AfA' | group == 'EA'| group == 'HSE'| group == 'HW'),];
colSums(is.na(eddat))
table(na.omit(dm6[,c(9,12,13,16,17,19,20,22,23,24,14,25,15,21,29)])$group)#18,,30

dm <- na.omit(dm6[,c(9,12,13,16,17,19,20,22,23,24,14,25,15,21,29)])
dm$group <- as.factor(dm$group)

dm <- cbind(dm["group"], scale(dm[,c(2:14)]) )
```

# time how long it takes

```{r, message=FALSE, warning=FALSE}

start_time <- Sys.time()
Accuracies <- c(0.00)
# suppress console output
sink('sinktest.txt')
for (i in seq(10))
{
  # sample
  inTrain <- createDataPartition(dm$group, p = .80, list = FALSE)
  dm.navg <- avNNet(dm[c(2:14)], dm$group, subset = inTrain, size = 2, rang = 0.5, decay = 5e-6, maxit = 200, repeats = 50)
  Accuracies[i] <- confusionMatrix(dm$group[-inTrain], predict(dm.navg, dm[-inTrain,], type = "class"))$overall["Accuracy"]
}
sink()
```

# turn output on again

```{r}
sink()
summary(Accuracies)
acclen = length(na.omit(Accuracies))
plot(density(Accuracies), main = paste('Average Neural Network Model accuracies:',acclen, 'runs') )

```


